##############################################
# User Service (Python/Flask)
# Command: docker compose up -d --build
# Pastikan rabbitmq/docker-compose.yml sudah berjalan
##############################################

services:
  userservice-app:
    build:
      context: .
    container_name: medtech-userservice
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@userservice-db/users_db
      - JWT_SECRET_KEY=HTELXPM5abn2unNMin7J!7^*&rmEKDUL188gH8NDbeaLrvHk!$@*&
      - RABBITMQ_HOST=medtech-rabbitmq
    volumes:
      - .:/app
    depends_on:
      userservice-db:
        condition: service_healthy
    networks:
      - medtech-network
    restart: unless-stopped

  userservice-db:
    image: mysql:8.0
    container_name: medtech-userservice-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - userservice_db_data:/var/lib/mysql
    networks:
      - medtech-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  medtech-network:
    external: true
    name: medtech-network

volumes:
  userservice_db_data:
